biolib_version: 2 #This specifies that the configuration file is written in version 2 of the BioLib configuration format.

modules: #This section defines the modules for your BioLib application. Modules are components of your application, and each module can have specific settings.
    main: #This is the name of the main module of your BioLib application.
        image: 'local-docker://deeplocrna-docker:latest' #This line specifies the Docker image that should be used for running the main module. It points to a local Docker image named deeplocrna-docker with the latest tag. This means that the BioLib application will run in a Docker container created from this image.
        command: python /home/DeepLocRNA/DeepLocRNA/fine_tuning_deeprbploc_allRNA_prediction.py  #This line specifies the command that should be executed within the Docker container when running the main module. In this case, it runs the /home/DeepLocRNA/run.sh script.
        working_directory: /home/DeepLocRNA/DeepLocRNA/ #This sets the working directory inside the Docker container to /home/DeepLocRNA/. Subsequent commands or operations within the container will be performed in this directory.
        input_files: #This section specifies the input files or data that should be made available to the BioLib application within the Docker container.
            - COPY / /home/DeepLocRNA/DeepLocRNA/ #This field defines where to copy the input files that are sent from the user of the application
        output_files:
            - COPY /home/DeepLocRNA/DeepLocRNA/output.csv / #This line indicates that all files and directories within the /home/DeepLocRNA/output/ directory of the Docker container should be copied to the root directory (/) of the container. This allows the BioLib application to output its results to this directory.
            - COPY /home/DeepLocRNA/DeepLocRNA/*.png / #copy all the .png files if exist
        source_files:
            - COPY /example.fasta /home/DeepLocRNA/DeepLocRNA/ #This line copies the sample.fasta file from the root (/) of the Docker container to the /home/graph-part/ directory inside the container. It provides the application with the necessary source fil
        # default_machine: 'gpu.small'
        gpu: required
output_type: markdown
arguments: 

    -   key: --fasta
        description: 'Input FASTA sequences to predict on.'
        key_value_separator: ' '
        default_value: 'example.fasta'
        type: text-file
        required: true


    -   key: --rna_types
        description: 'Select RNA types'
        key_value_separator: ' '
        default_value: 'mRNA'
        type: dropdown
        options:
           'mRNA': 'mRNA'
           'miRNA': 'miRNA'
           'lncRNA': 'lncRNA'
           'snRNA': 'snRNA'
           'snoRNA': 'snoRNA'
        required: true

    -   key: --plot
        description: 'Whether to plot the full-length attribution'
        key_value_separator: ' '
        default_value: "False"
        type: toggle
        options:
           'on': 'True'
           'off': 'False'   
        required: true

    -   key: --att_config
        description: 'self-defined file to plot the precise attribution'
        key_value_separator: ' '
        default_value: None
        type: text-file
        required: true

    -   key: --species
        description: 'Select species'
        key_value_separator: ' '
        default_value: 'Human'
        type: dropdown
        options:
           'Human': 'Human'
           'Mouse': 'Mouse'
        required: true

license_file: LICENSE

citation:
    entry_type: article
    author: Jun Wang, Marc Horlacher, Ole Winther
    title: DeepLocRNA-An Interpretable Deep Learning Model for Deriving RNA Subcellular Localization with domain-specific transfer-learning
    publisher: unknown
    year: '2023'
    doi: unknown
    journal: unknown
    URL: unknow
    eprint: unknow
