name: CI

on: 
    push: #(required)trigger this event if someone use push of this repository, # more trigger events can refer to: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
        branches: [ main ]
    pull_request:
        branches: [ main ]
env:
    BIOLIB_LOG: debug
    BIOLIB_PROJECT_URI: KU/DeepLocRNA
    LOCAL_DOCKER_TAG: deeplocrna-docker:latest

#Then the workflow get executed followed by several actions.
jobs:
    build-and-publish:
        name: Build Docker image and publish if on main
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                
            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8
                    
            -   name: Build docker image
                run: docker build -t $LOCAL_DOCKER_TAG -f webserver/Dockerfile .

            -   name: check file
                run: |
                    docker run deeplocrna-docker:latest ls /home/DeepLocRNA
                    docker run deeplocrna-docker:latest ls /home/DeepLocRNA/DeepLocRNA
                    # docker run deeplocrna-docker:latest nvidia-smi

            -   name: Install BioLib CLI
                run: pip3 install -U pybiolib

            -   name: Publish new version to BioLib if on main branch
                #if: github.ref == 'refs/heads/developer2'
 
                run: cd webserver && biolib push $BIOLIB_PROJECT_URI
                env:
                    BIOLIB_TOKEN: ${{ secrets.BIOLIB_TOKEN }}
