name: CI

on: push #(required)trigger this event if someone use push of this repository, 
         # more trigger events can refer to: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

env:
    BIOLIB_LOG: debug
    BIOLIB_PROJECT_URI: KU/DeepLocRNA
    LOCAL_DOCKER_TAG: DeepLocRNA-docker:latest
#Then the workflow get executed followed by several actions.
jobs: #(Required)
    build-and-publish: #The name of the job, which have sevaral actions
        name: Build Docker image and publish if on main
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2#CI/CD has to check out whether their working env is workable

            -   name: Build docker image
                run: docker build -t $LOCAL_DOCKER_TAG -f webserver/Dockerfile .

            -   name: Setup Python
                uses: actions/setup-python@v2#prepare your python env
                with:
                    python-version: 3.8#python version 3.8 will be installed

            -   name: Install BioLib CLI
                run: pip3 install pybiolib #run the linux command, just use run attribute

            -   name: Publish new version to BioLib if on main branch
                if: github.ref == 'refs/heads/main'
                run: cd webserver && biolib push $BIOLIB_PROJECT_URI
                env:
                    BIOLIB_TOKEN: ${{ secrets.BIOLIB_TOKEN }}
